export const categoryElement: string;
export const categoryPlaceholder: string;
export const container: string;
export const fakeClass: string;
export const itemElement: string;
export const itemPlaceholder: string;
export const itemWrapper: string;
export const materialElement: string;
export const materialPlaceholder: string;
