export const addBtn: string;
export const addOrderStringBtn: string;
export const container: string;
export const creationOrderWindowBody: string;
export const fakeClass: string;
export const header: string;
export const middleContainer: string;
export const orderItemsBorder: string;
export const textArea: string;
