export const container: string;
export const fakeClass: string;
export const input: string;
export const inputGroup: string;
export const inputWrapper: string;
export const loginBlockText: string;
export const loginBtn: string;
export const loginWindowBody: string;
export const loginWrapper: string;
